[package]
name = "webhook_error_reporter_core"
version = "0.1.0"
authors = ["thinkier <26728734+thinkier@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hyper-tls="^0.4.1"
hyper="^0.14.10"
serde="^1.0.114"
serde_json="^1.0.56"

[features]
split_msg=[]
